/*
 * eGov Water and Sewerage(W&S)  System.
 * APIs for W&S module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Contract class to receive request. Array of Property items  are used in case of create . Where as single Property item is used for update
 */
@Schema(description = "Contract class to receive request. Array of Property items  are used in case of create . Where as single Property item is used for update")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T12:10:41.195Z[GMT]")
public class SewerageConnectionRequest {
  @JsonProperty("RequestInfo")
  private RequestInfo requestInfo = null;

  @JsonProperty("SewerageConnection")
  private SewerageConnection sewerageConnection = null;

  public SewerageConnectionRequest requestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
    return this;
  }

   /**
   * Get requestInfo
   * @return requestInfo
  **/
  @Schema(description = "")
  public RequestInfo getRequestInfo() {
    return requestInfo;
  }

  public void setRequestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
  }

  public SewerageConnectionRequest sewerageConnection(SewerageConnection sewerageConnection) {
    this.sewerageConnection = sewerageConnection;
    return this;
  }

   /**
   * Get sewerageConnection
   * @return sewerageConnection
  **/
  @Schema(description = "")
  public SewerageConnection getSewerageConnection() {
    return sewerageConnection;
  }

  public void setSewerageConnection(SewerageConnection sewerageConnection) {
    this.sewerageConnection = sewerageConnection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SewerageConnectionRequest sewerageConnectionRequest = (SewerageConnectionRequest) o;
    return Objects.equals(this.requestInfo, sewerageConnectionRequest.requestInfo) &&
        Objects.equals(this.sewerageConnection, sewerageConnectionRequest.sewerageConnection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestInfo, sewerageConnection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SewerageConnectionRequest {\n");
    
    sb.append("    requestInfo: ").append(toIndentedString(requestInfo)).append("\n");
    sb.append("    sewerageConnection: ").append(toIndentedString(sewerageConnection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
