/*
 * eGov Water and Sewerage(W&S)  System.
 * APIs for W&S module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Contains the ResponseHeader and the created/updated property
 */
@Schema(description = "Contains the ResponseHeader and the created/updated property")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T12:10:41.195Z[GMT]")
public class SewerageConnectionResponse {
  @JsonProperty("ResponseInfo")
  private ResponseInfo responseInfo = null;

  @JsonProperty("SewerageConnections")
  private List<SewerageConnection> sewerageConnections = null;

  public SewerageConnectionResponse responseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
    return this;
  }

   /**
   * Get responseInfo
   * @return responseInfo
  **/
  @Schema(description = "")
  public ResponseInfo getResponseInfo() {
    return responseInfo;
  }

  public void setResponseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
  }

  public SewerageConnectionResponse sewerageConnections(List<SewerageConnection> sewerageConnections) {
    this.sewerageConnections = sewerageConnections;
    return this;
  }

  public SewerageConnectionResponse addSewerageConnectionsItem(SewerageConnection sewerageConnectionsItem) {
    if (this.sewerageConnections == null) {
      this.sewerageConnections = new ArrayList<SewerageConnection>();
    }
    this.sewerageConnections.add(sewerageConnectionsItem);
    return this;
  }

   /**
   * Get sewerageConnections
   * @return sewerageConnections
  **/
  @Schema(description = "")
  public List<SewerageConnection> getSewerageConnections() {
    return sewerageConnections;
  }

  public void setSewerageConnections(List<SewerageConnection> sewerageConnections) {
    this.sewerageConnections = sewerageConnections;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SewerageConnectionResponse sewerageConnectionResponse = (SewerageConnectionResponse) o;
    return Objects.equals(this.responseInfo, sewerageConnectionResponse.responseInfo) &&
        Objects.equals(this.sewerageConnections, sewerageConnectionResponse.sewerageConnections);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseInfo, sewerageConnections);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SewerageConnectionResponse {\n");
    
    sb.append("    responseInfo: ").append(toIndentedString(responseInfo)).append("\n");
    sb.append("    sewerageConnections: ").append(toIndentedString(sewerageConnections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
