/*
 * eGov Water and Sewerage(W&S)  System.
 * APIs for W&S module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Contains the ResponseHeader and the created/updated property
 */
@Schema(description = "Contains the ResponseHeader and the created/updated property")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-26T12:10:41.195Z[GMT]")
public class WaterConnectionResponse {
  @JsonProperty("ResponseInfo")
  private ResponseInfo responseInfo = null;

  @JsonProperty("WaterConnection")
  private List<WaterConnection> WaterConnection = null;

  public WaterConnectionResponse responseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
    return this;
  }

   /**
   * Get responseInfo
   * @return responseInfo
  **/
  @Schema(description = "")
  public ResponseInfo getResponseInfo() {
    return responseInfo;
  }

  public void setResponseInfo(ResponseInfo responseInfo) {
    this.responseInfo = responseInfo;
  }

  public WaterConnectionResponse waterConnection(List<WaterConnection> waterConnection) {
    this.WaterConnection = waterConnection;
    return this;
  }

  public WaterConnectionResponse addWaterConnectionItem(WaterConnection waterConnectionItem) {
    if (this.WaterConnection == null) {
      this.WaterConnection = new ArrayList<WaterConnection>();
    }
    this.WaterConnection.add(waterConnectionItem);
    return this;
  }

   /**
   * Get waterConnection
   * @return waterConnection
  **/
  @Schema(description = "")
  public List<WaterConnection> getWaterConnection() {
    return WaterConnection;
  }

  public void setWaterConnection(List<WaterConnection> waterConnection) {
    this.WaterConnection = waterConnection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WaterConnectionResponse waterConnectionResponse = (WaterConnectionResponse) o;
    return Objects.equals(this.responseInfo, waterConnectionResponse.responseInfo) &&
        Objects.equals(this.WaterConnection, waterConnectionResponse.WaterConnection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseInfo, WaterConnection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WaterConnectionResponse {\n");
    
    sb.append("    responseInfo: ").append(toIndentedString(responseInfo)).append("\n");
    sb.append("    waterConnection: ").append(toIndentedString(WaterConnection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
