---
ReportDefinitions:
- reportName: TradeLicenseRegistryReport
  summary: TL Basic Report
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: licensenumber
    label: report.tl.licensenumber
    type: string
    source: tl
    total: false
  - name: formattedIssuedDate
    label: report.tl.issueddate
    type: string
    source: tl
    total: false
  - name: name
    label: report.tl.user.name
    type: string
    source: tl
    total: false
  - name: mobilenumber
    label: report.tl.user.mobilenumber
    type: string
    source: tl
    total: false
  - name: tradeTypeName
    label: report.tl.tradetype
    type: string
    source: tl
    total: true
  - name: acc
    label: report.tl.accessorycategories
    type: string
    source: tl
    total: false
  - name: tradeName
    label: report.tl.tradeName
    type: string
    source: tl
    total: false
  - name: totalamount
    label: report.tl.receipt.totalamount
    type: string
    source: tl
    total: false
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate <= $toDate
  query: SELECT licensenumber,to_char(To_timestamp(issueddate / 1000), 'DD/MM/YYYY') as formattedIssuedDate,tl.tradeName,tradeTypeName,acc, name,mobilenumber,totalamount FROM eg_tl_tradelicense tl INNER JOIN eg_tl_tradelicensedetail tld ON tld.tradelicenseid = tl.id INNER JOIN eg_tl_owner tlowner ON tlowner.tradelicensedetailid = tld.id INNER JOIN (SELECT tradelicensedetailid,message.message as tradeTypeName FROM eg_tl_tradeunit INNER JOIN message ON split_part(message.code,'_',2) = tradeType) tlunit ON tlunit.tradelicensedetailid = tld.id INNER JOIN eg_user tluser ON tluser.uuid = tlowner.id LEFT OUTER JOIN egcl_receiptheader receipt ON receipt.consumercode = tl.applicationnumber LEFT OUTER JOIN (SELECT tradelicensedetailid,array_to_string(array_agg(message.message),',') AS acc FROM eg_tl_accessory LEFT OUTER JOIN message ON split_part(message.code,'_',2) = accessorycategory AND message.locale = 'en_IN' GROUP BY 1 ) tlacc ON tlacc.tradelicensedetailid = tld.id WHERE tl.Status = 'APPROVED' AND tl.tenantId LIKE $tenantid



- reportName: TradeWiseCollectionReport
  summary: Collection according to tradeTypes
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: tradeSubType
    label: report.tl.tradeType
    type: string
    source: tl
    total: false
  - name: transactionNumber
    label: report.tl.totalTransaction
    type: string
    source: tl
    total: false
  - name: online
    label: report.tl.online.collection
    type: string
    source: tl
    total: true
  - name: offline
    label: report.tl.offline.collection
    type: string
    source: tl
    total: true
  - name: total
    label: report.tl.totalCollection
    type: string
    source: tl
    total: true
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate <= $toDate
  query:  SELECT COUNT(applicationNumber) as transactionNumber,tradeSubType,SUM(onl.totalAmount) as online,SUM(offl.totalAmount) as offline, COALESCE(SUM(onl.totalAmount),0)+ COALESCE(SUM(offl.totalAmount),0) as total FROM eg_tl_tradelicense tl INNER JOIN eg_tl_tradelicensedetail tld ON tld.tradelicenseid = tl.id INNER JOIN (SELECT tradelicensedetailid,message.message as tradeSubType FROM eg_tl_tradeunit LEFT OUTER JOIN message ON CONCAT('TL_',split_part(tradeType, '.', 2)) = message.code AND message.locale='en_IN') tlunit ON tlunit.tradelicensedetailid = tld.id LEFT OUTER JOIN (SELECT * FROM egcl_receiptheader WHERE collectiontype = 'ONLINE') AS onl ON onl.consumercode = tl.applicationnumber LEFT OUTER JOIN (SELECT * FROM egcl_receiptheader WHERE collectiontype = 'COUNTER') AS offl ON offl.consumercode = tl.applicationnumber WHERE tl.status IN ('APPROVED','PAID','REJECTED') AND tl.tenantId LIKE $tenantid
  groupby: GROUP BY tradeSubType


- reportName: TradeLicenseApplicationStatusReport
  summary: Nummber of applications by there status
  version: 1.0.0
  moduleName: rainmaker-tl
  externalService:
  - entity: $.messages[*]
    apiURL: http://egov-localization:8080/localization/messages/v1/_search?locale=en_IN&tenantId=pb&module=rainmaker-tl
    keyOrder: code,message
    tableName: tbl_localization
  sourceColumns:
  - name: status
    label: report.tl.status
    type: string
    source: tl
    total: false
  - name: total
    label: report.tl.total
    type: string
    source: tl
    total: true
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND tl.lastmodifiedtime >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND tl.lastmodifiedtime <= $toDate
  query: SELECT COUNT(applicationnumber) as total,message.message as status from eg_tl_tradelicense tl LEFT OUTER JOIN message ON split_part(message.code,'_',2) = status AND message.locale = 'en_IN' WHERE tl.tenantid LIKE $tenantid
  groupby: GROUP BY message.message
  orderby: ORDER BY case message.message when 'Pending Application' then 1 when 'Pending Payment' then 2 when 'Pending Approval' then 3 when 'Approved' then 4 when 'Rejected' then 5 when 'Cancelled' then 6 else 7 end

- reportName: StateLevelStatus
  summary: Nummber of applications by there status state level
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: status
    label: report.tl.status
    type: string
    source: tl
    total: false
  - name: total
    label: report.tl.total
    type: string
    source: tl
    total: true
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND tl.lastmodifiedtime >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND tl.lastmodifiedtime <= $toDate
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: tl
    wrapper: true
    isMandatory: false
    searchClause: AND tl.tenantId = $ulb
  query: SELECT COUNT(applicationnumber) as total,message.message as status from eg_tl_tradelicense tl LEFT OUTER JOIN message ON split_part(message.code,'_',2) = status AND message.locale = 'en_IN' WHERE 1=1
  groupby: GROUP BY message.message
  orderby: ORDER BY case message.message when 'Pending Application' then 1 when 'Pending Payment' then 2 when 'Pending Approval' then 3 when 'Approved' then 4 when 'Rejected' then 5 when 'Cancelled' then 6 else 7 end



- reportName: StateLevelTradeWiseCollection
  summary: Collection according to tradeTypes state level
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: tenantId
    label: report.tl.tenantid
    type: string
    source: tl
    total: false
  - name: tradeSubType
    label: report.tl.tradeType
    type: string
    source: tl
    total: false
  - name: transactionNumber
    label: report.tl.totalTransaction
    type: string
    source: tl
    total: true
  - name: online
    label: report.tl.online.collection
    type: string
    source: tl
    total: true
  - name: offline
    label: report.tl.offline.collection
    type: string
    source: tl
    total: true
  - name: total
    label: report.tl.totalCollection
    type: string
    source: tl
    total: true
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate <= $toDate
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: tl
    wrapper: true
    isMandatory: false
    searchClause: AND tl.tenantId = $ulb
  query:   SELECT COUNT(applicationNumber) as transactionNumber,tradeSubType,SUM(onl.totalAmount) as online,SUM(offl.totalAmount) as offline, COALESCE(SUM(onl.totalAmount),0)+ COALESCE(SUM(offl.totalAmount),0) as total,initcap(split_part(tl.tenantId, '.', 2)) as tenantId FROM eg_tl_tradelicense tl INNER JOIN eg_tl_tradelicensedetail tld ON tld.tradelicenseid = tl.id INNER JOIN (SELECT tradelicensedetailid,message.message as tradeSubType FROM eg_tl_tradeunit LEFT OUTER JOIN message ON CONCAT('TL_',split_part(tradeType, '.', 2)) = message.code AND message.locale='en_IN') tlunit ON tlunit.tradelicensedetailid = tld.id LEFT OUTER JOIN (SELECT * FROM egcl_receiptheader WHERE collectiontype = 'ONLINE') AS onl ON onl.consumercode = tl.applicationnumber LEFT OUTER JOIN (SELECT * FROM egcl_receiptheader WHERE collectiontype = 'COUNTER') AS offl ON offl.consumercode = tl.applicationnumber WHERE tl.status IN ('APPROVED','PAID','REJECTED')
  groupby: GROUP BY tl.tenantId,tradeSubType
  orderby: ORDER BY tl.tenantId asc


- reportName: StateLevelTradeLicenseRegistryReport
  summary: TL Basic Report State Level
  version: 1.0.0
  moduleName: rainmaker-tl
  sourceColumns:
  - name: tenantId
    label: report.tl.tenantId
    type: string
    source: tl
    total: false
  - name: licensenumber
    label: report.tl.licensenumber
    type: string
    source: tl
    total: false
  - name: formattedIssuedDate
    label: report.tl.issueddate
    type: string
    source: tl
    total: false
  - name: name
    label: report.tl.user.name
    type: string
    source: tl
    total: false
  - name: mobilenumber
    label: report.tl.user.mobilenumber
    type: string
    source: tl
    total: false
  - name: tradeTypeName
    label: report.tl.tradetype
    type: string
    source: tl
    total: true
  - name: acc
    label: report.tl.accessorycategories
    type: string
    source: tl
    total: false
  - name: tradeName
    label: report.tl.tradeName
    type: string
    source: tl
    total: false
  - name: totalamount
    label: report.tl.receipt.totalamount
    type: string
    source: tl
    total: false
  searchParams:
  - name: fromDate
    label: reports.tl.fromDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate >= $fromDate
  - name: toDate
    label: reports.tl.toDate
    type: epoch
    source: tl
    isMandatory: false
    searchClause: AND issueddate <= $toDate
  - name: ulb
    label: ULB
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
    source: tl
    wrapper: true
    isMandatory: false
    searchClause: AND tl.tenantId = $ulb
  query: SELECT tl.tenantId as tenantId,licensenumber,to_char(To_timestamp(issueddate / 1000), 'DD/MM/YYYY') as formattedIssuedDate,tl.tradeName,tradeTypeName,acc, name,mobilenumber,totalamount FROM eg_tl_tradelicense tl INNER JOIN eg_tl_tradelicensedetail tld ON tld.tradelicenseid = tl.id INNER JOIN eg_tl_owner tlowner ON tlowner.tradelicensedetailid = tld.id INNER JOIN (SELECT tradelicensedetailid,message.message as tradeTypeName FROM eg_tl_tradeunit INNER JOIN message ON split_part(message.code,'_',2) = tradeType) tlunit ON tlunit.tradelicensedetailid = tld.id INNER JOIN eg_user tluser ON tluser.uuid = tlowner.id LEFT OUTER JOIN egcl_receiptheader receipt ON receipt.consumercode = tl.applicationnumber LEFT OUTER JOIN (SELECT tradelicensedetailid,array_to_string(array_agg(message.message),',') AS acc FROM eg_tl_accessory LEFT OUTER JOIN message ON split_part(message.code,'_',2) = accessorycategory AND message.locale = 'en_IN' GROUP BY 1 ) tlacc ON tlacc.tradelicensedetailid = tld.id WHERE tl.Status = 'APPROVED'
  orderby: ORDER BY tl.tenantId asc

