ReportDefinitions:
  - reportName: CollectionRegister
    summary: Collection Register
    version: 1.0.0
    moduleName: rainmaker-uc
    externalService:
    - entity: $.MdmsRes.BillingService.BusinessService[*] 
      apiURL: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=BillingService&masterName=BusinessService&filter=[?(@.type=='Adhoc')]
      keyOrder: code,businessService
      tableName: tbl_businessserviceList
    sourceColumns:
      - name: service
        label: reports.common.CollectionRegister.serviceResult
        type: string
        source: common
        total: false
      - name: channel
        label: reports.common.CollectionRegister.channel
        type: string
        source: common
        total: false
      - name: cash_count
        label: reports.common.CollectionRegister.transactions
        type: string
        source: common
        total: false
      - name: cash_sum
        label: reports.common.CollectionRegister.cash
        type: string
        source: common
        total: true
      - name: cheque_count
        label: reports.common.CollectionRegister.transactions
        type: string
        source: common
        total: false
      - name: cheque_sum
        label: reports.common.CollectionRegister.cheque
        type: string
        source: common
        total: true
      - name: dd_count
        label: reports.common.CollectionRegister.transactions
        type: string
        source: common
        total: false
      - name: dd_sum
        label: reports.common.CollectionRegister.dd
        type: string
        source: common
        total: true
      - name: online_count
        label: reports.common.CollectionRegister.transactions
        type: string
        source: common
        total: false
      - name: online_sum
        label: reports.common.CollectionRegister.online
        type: string
        source: common
        total: true
      - name: card_count
        label: reports.common.CollectionRegister.transactions
        type: string
        source: common
        total: false
      - name: card_sum
        label: reports.common.CollectionRegister.card
        type: string
        source: common
        total: true
      - name: total
        label: reports.common.CollectionRegister.total
        type: string
        source: common
        total: true

    searchParams:
      - name: ulb
        label: reports.common.CollectionRegister.ulb
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: common
        wrapper: true
        isMandatory: true
        searchClause: AND rt.tenantId = $ulb
      - name: service
        label: reports.common.CollectionRegister.service
        type: multivaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=BillingService&masterName=BusinessService&filter=[?(@.type=='Adhoc')]|$.MdmsRes.BillingService.BusinessService.*.code|$.MdmsRes.BillingService.BusinessService.*.businessService
        source: common
        wrapper: true
        state: true
        isMandatory: true
        isLocalisationRequired: true
        searchClause: AND REGEXP_REPLACE(rt.businessdetails,'\..*','') IN ($service)
      - name: paymentMode
        label: reports.common.CollectionRegister.mode
        type: singlevaluelist
        pattern: 'list://Cash:Cash,Online:Online,Card:Card,DD:DD,Cheque:Cheque'
        source: common
        isMandatory: false
        searchClause: AND instrumenttype = $paymentMode
      - name: channel
        label: reports.common.CollectionRegister.channel
        type: singlevaluelist
        pattern: 'list://COUNTER:COUNTER,FIELD:FIELD'
        source: common
        isMandatory: false
        searchClause: AND collectiontype = $channel
      - name: fromDate
        label: reports.common.CollectionRegister.fromdate
        type: epoch
        source: common
        isMandatory: true
        searchClause: AND receiptdate >= $fromDate
      - name: toDate
        label: reports.common.CollectionRegister.todate
        type: epoch
        source: common
        isMandatory: true
        searchClause: AND receiptdate <= $toDate

    query: select COALESCE(message,REGEXP_REPLACE(businessdetails,'\..*','')) service,collectiontype channel,sum(case when instrumenttype='Cash' then 1 else 0 end) as cash_count, sum(case when instrumenttype='Cash' then ins.amount else 0 end) as cash_sum, sum(case when instrumenttype='Cheque' then 1 else 0 end) as cheque_count, sum(case when instrumenttype='Cheque' then ins.amount else 0 end) as cheque_sum, sum(case when instrumenttype='DD' then 1 else 0 end) as dd_count, sum(case when instrumenttype='DD' then ins.amount else 0 end) as dd_sum, sum(case when instrumenttype='Online' then 1 else 0 end) as online_count, sum(case when instrumenttype='Online' then ins.amount else 0 end) as online_sum, sum(case when instrumenttype='Card' then 1 else 0 end) as card_count, sum(case when instrumenttype='Card' then amount else 0 end) as card_sum,sum(amount) total from egcl_receiptheader_v1 rt inner join egcl_receiptinstrument_v1 ihead on rt.id=receiptheader inner join egcl_instrumentheader_v1 ins on instrumentheader=ins.id left outer join message on LOWER(concat('BILLINGSERVICE_BUSINESSSERVICE_',REGEXP_REPLACE(businessdetails,'\..*','')))=LOWER(code)  AND module='rainmaker-uc' where businessdetails IN (select code from (VALUES tbl_businessserviceList) AS serv_list(code,servicename))
    groupby: group by service,collectiontype
    orderby: order by service,collectiontype

  - reportName: MiscReceipt
    summary: Receipt Register Miscellaneous
    version: 1.0.0
    moduleName: rainmaker-uc
    sourceColumns:
      - name: ulb
        label: reports.uc.ulb
        type: string
        source: uc
        total: false
      - name: receiptnumber
        label: reports.uc.receiptnumber
        type: string
        source: uc
        total: false
      - name: redeiptdate
        label: reports.uc.receiptdate
        type: string
        source: uc
        total: false
      - name: g8issuedate
        label: reports.uc.g8issuedate
        type: string
        source: uc
        total: false
      - name: g8receiptno
        label: reports.uc.g8receiptno
        type: string
        source: uc
        total: false
      - name: status
        label: reports.uc.receiptstatus
        type: string
        source: uc
        total: false
      - name: servicecategory
        label: reports.uc.businessdetails
        type: string
        source: uc
        total: false
      - name: gst
        label: reports.uc.gst
        type: string
        source: uc
        total: true
      - name: tax
        label: reports.uc.tax
        type: string
        source: uc
        total: true
      - name: fieldcollection
        label: reports.uc.fieldcollection
        type: string
        source: uc
        total: true
      - name: fee
        label: reports.uc.fee
        type: string
        source: uc
        total: true
      - name: ddorchequenumber
        label: reports.uc.ddorchecquenumber
        type: string
        source: uc
        total: false
      - name: collectiontype
        label: reports.uc.collectiontype
        type: string
        source: uc
        total: false
      - name: collectorname
        label: reports.uc.collectorname
        type: string
        source: uc
        total: false
      - name: totalamount
        label: reports.uc.totalamount
        type: string
        source: uc
        total: true
      - name: paymentmode
        label: reports.uc.paymentmode
        type: string
        source: uc
        total: false
    searchParams:
      - name: fromDate
        label: reports.uc.fromDate
        type: epoch
        source: uc
        isMandatory: false
        searchClause: AND rh.receiptdate >= $fromDate
      - name: toDate
        label: reports.uc.toDate
        type: epoch
        source: uc
        isMandatory: false
        searchClause: AND rh.receiptdate <= $toDate
      - name: ulb
        label: reports.uc.ulb
        type: singlevaluelist
        pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=$tenantid&moduleName=tenant&masterName=tenants|$.MdmsRes.tenant.tenants.*.code|$.MdmsRes.tenant.tenants.*.name
        source: uc
        wrapper: true
        isMandatory: false
        searchClause: AND rh.tenantid = $ulb
    query: |
        -- Use CTE to force query plan, compute & use CTE later
        WITH receipt_breakup AS (
                    SELECT 
                      receiptheader, 
                      SUM(CASE WHEN taxheadcode LIKE '%_CGST' THEN adjustedamount ELSE 0 END) as gst, 
                      SUM(CASE WHEN taxheadcode LIKE '%_TAX' THEN adjustedamount ELSE 0 END) as tax, 
                      SUM(CASE WHEN taxheadcode LIKE '%_FIELD' THEN adjustedamount ELSE 0 END) as fieldcollection, 
                      SUM(CASE WHEN taxheadcode LIKE '%_FEE' THEN adjustedamount ELSE 0 END) as fee            
                    FROM egcl_receiptdetails_v1 as rd
                    INNER JOIN egcl_receiptheader_v1 as rh on rh.id = rd.receiptheader
                    GROUP BY rd.receiptheader
        )
        SELECT 
          rh.tenantid as ulb,
          rh.receiptnumber as receiptnumber,
          To_char(To_timestamp(rh.receiptdate / 1000), 'DD/MM/YYYY') as receiptdate,
          To_char(To_timestamp(rh.manualreceiptdate / 1000), 'DD/MM/YYYY') as g8issuedate,
          rh.manualreceiptnumber as g8receiptno,
          rh.status as status,
          businessdetails as servicecategory,
          receipt_breakup.*,  
          amount as totalamount, 
          instrumenttype as paymentmode,
          (case when instrumenttype like 'Cash' then '' else  transactionnumber end) as ddorchequenumber,
          'System' as collectiontype,
          eg_user.name as collectorname
        FROM egcl_receiptheader_v1 AS rh
        JOIN egcl_receiptinstrument_v1 AS ri ON rh.id = ri.receiptheader
        JOIN egcl_instrumentheader_v1 AS ih ON ih.id = ri.instrumentheader
        JOIN receipt_breakup ON rh.id = receipt_breakup.receiptheader
        JOIN eg_user ON rh.createdby::INTEGER=eg_user.id
        WHERE  rh.status != 'Cancelled'  AND receiptnumber like 'MP%'
    orderby: ORDER BY rh.receiptdate DESC

