insert into tmp_boundary (digitname,digitcode) values (	'Jagara Railway crossing to left side to jagara octria. Block 1A - B1A - A1',	'Ahd_1'	);
insert into tmp_boundary (digitname,digitcode) values (	'Pohir Octrci to railway crossing left and right side Guru Nanak Nagar Pohir Road Block 1A - B1A - A1',	'Ahd_2'	);
insert into tmp_boundary (digitname,digitcode) values (	'Shakti Industirs New tellphone exchange left and right side. Block 1A - B1A - A1',	'Ahd_3'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bus stand to Opposite Gadown Area, Bus stand Nal wali Road Block 1A - B1A - A1',	'Ahd_4'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagara Road to pohir road bye pass main road to away from 30 feet Block 1A - B1A - A1',	'Ahd_5'	);
insert into tmp_boundary (digitname,digitcode) values (	'Area for white House, Gadown Jagara road, Pohir Road swastik colony. And Near Colonies Block 1A - B1A - A1',	'Ahd_6'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagara road near back bye pass left and right side, Area for shakti Industries, Block 1A - B1A - A1',	'Ahd_7'	);
insert into tmp_boundary (digitname,digitcode) values (	'Railway Jagera road to new tempo union opp railway station colony road, Block 1A - B1A - A1',	'Ahd_8'	);
insert into tmp_boundary (digitname,digitcode) values (	'subhash kohallu. De nal jagara road, Near railway line Colony F.C.I. Block 1A - B1A - A1',	'Ahd_9'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back side Gadown Bhatti sewak. Block 1A - B1A - A1',	'Ahd_10'	);
insert into tmp_boundary (digitname,digitcode) values (	'Second side link road Jandali both side about 400 meter to (Jandali side) Area 200 foot about deeply. Block 2A - B2A - A1',	'Ahd_11'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ludhiana Malerkotla road left and right side, Malerkotla to ludhiana road, link road left and right side Block 2A - B2A - A1',	'Ahd_12'	);
insert into tmp_boundary (digitname,digitcode) values (	'momnabad road upto ahmedgarh Limit. Every comm and indus Area Block 2A - B2A - A1',	'Ahd_13'	);
insert into tmp_boundary (digitname,digitcode) values (	'Right side Ludhiana malerkotla road about 300 foot deeply. Block 2A - B2A - A1',	'Ahd_14'	);
insert into tmp_boundary (digitname,digitcode) values (	'Shryans Industries Area, Octrio Jagara Opposite Main road away from 30 feet back side area. Block 2A - B2A - A1',	'Ahd_15'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagera railway crossing to octria Jagera right side. Block 2A - B2A - A1',	'Ahd_16'	);
insert into tmp_boundary (digitname,digitcode) values (	'Link road Jandali 400 meter away from main road both side approximate 300 foot deeply up to BEPO office. Block 2A - B2A - A1',	'Ahd_17'	);
insert into tmp_boundary (digitname,digitcode) values (	'Right side railway crossing to Aruvrat chowk Block 3 - B3 - A1',	'Ahd_18'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dhurkot Chowk upto limit durkot octri right side. Block 3 - B3 - A1',	'Ahd_19'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ujjagar Petrol Pump to Jaga scootra wala both side durkot road, Bhagwan Nagar streets Block 3 - B3 - A1',	'Ahd_20'	);
insert into tmp_boundary (digitname,digitcode) values (	'Amarpura Mohalla Every street, Kamal Rice mill Area, Joga Scooter wall streets. Block 3 - B3 - A1',	'Ahd_21'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dhurkot Chowk upto Octria dhurkot Left side, Every streets Dashmesh nagar, Nahar Singh gadown. Block 4 - B4 - A1',	'Ahd_22'	);
insert into tmp_boundary (digitname,digitcode) values (	'Railway crossing to anuwrat chowk left side. Block 5 - B5 - A1',	'Ahd_23'	);
insert into tmp_boundary (digitname,digitcode) values (	'Anuvrat chowk to railway chowk both side. Block 5 - B5 - A1',	'Ahd_24'	);
insert into tmp_boundary (digitname,digitcode) values (	'Left and right side old truck union, Back side central bank and hari chand baba streets. Block 5 - B5 - A1',	'Ahd_25'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mahavir road right side Jeet Boot house upto 30 foot deeply. Block 5 - B5 - A1',	'Ahd_26'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vijay tandan side, sanjav sharma wali street. Block 5 - B5 - A1',	'Ahd_27'	);
insert into tmp_boundary (digitname,digitcode) values (	'Municipal council nal wali street from upto new tahsil. Block 6 - B6 - A1',	'Ahd_28'	);
insert into tmp_boundary (digitname,digitcode) values (	'Both side charua Bazar, Main bazar, grain market both sides 30 foot deeply. Block 6 - B6 - A1',	'Ahd_29'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kaku electronic chowk. Block 6 - B6 - A1',	'Ahd_30'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bank road right side Block 6 - B6 - A1',	'Ahd_31'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagara crossing upto Guru Dhwara Singh sabha, right side chowk. Block 6 - B6 - A1',	'Ahd_32'	);
insert into tmp_boundary (digitname,digitcode) values (	'Tempo Adda to B.R. Amadakar chowk upto both side 30 foot deeply guru teg bahadur market. Block 6 - B6 - A1',	'Ahd_33'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bank road left side. Block 7 - B7 - A1',	'Ahd_34'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mahavir road left side Jeet Boot house upto 30 foot deeply. Block 7 - B7 - A1',	'Ahd_35'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kunan lal hospital road upto limit, Green Avenue Block 7 - B7 - A1',	'Ahd_36'	);
insert into tmp_boundary (digitname,digitcode) values (	'Area dr. Kundan Lal hospital, Lakashmi Narayan mandir \'s streets. Block 7 - B7 - A1',	'Ahd_37'	);
insert into tmp_boundary (digitname,digitcode) values (	'T.W. No 2 de opposite Area, Mahavir road back side Area. Block 7 - B7 - A1',	'Ahd_38'	);
insert into tmp_boundary (digitname,digitcode) values (	'Hind hospital, Ram sharnam Ashram to right side yash painter Area Block 8 - B8 - A1',	'Ahd_39'	);
insert into tmp_boundary (digitname,digitcode) values (	'Model town, Right side gainy upto gandhi school Area, Datta Ram schools streets. Block 8 - B8 - A1',	'Ahd_40'	);
insert into tmp_boundary (digitname,digitcode) values (	'Railway road left side up to thana road. Block 8 - B8 - A1',	'Ahd_41'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagara crossing to Gurudwara singh Sabha upto left side chownk. Block 8 - B8 - A1',	'Ahd_42'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gurudwara Bhai vir Singh Road to hind hospital Both side. Block 8 - B8 - A1',	'Ahd_43'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back side Bhai Vir singh Area. Block 8 - B8 - A1',	'Ahd_44'	);
insert into tmp_boundary (digitname,digitcode) values (	'Colony thana road, Near lakhshmi ice factory, right side Area , Thana road. Block 8 - B8 - A1',	'Ahd_45'	);
insert into tmp_boundary (digitname,digitcode) values (	'Railway road right side gurudwara singh Sabha up to Jain School road Block 9A - B9A - A1',	'Ahd_46'	);
insert into tmp_boundary (digitname,digitcode) values (	'Batta Bagh, Tagore Nagar, Jawahar Nagar, Mohalla kaser wala. Block 9A - B9A - A1',	'Ahd_47'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bhagat Singh Chownk to Gandhi Chownk Both side Block 10A - B10A - A1',	'Ahd_48'	);
insert into tmp_boundary (digitname,digitcode) values (	'Tahsil Chowk both side, Gandhi Chowk up to old tahsil chowk Block 10A - B10A - A1',	'Ahd_49'	);
insert into tmp_boundary (digitname,digitcode) values (	'Area inspector piarye lal house. Block 10A - B10A - A1',	'Ahd_50'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla chaudhary brij lal, Area Nav Bahar, Shiv Puri Mohalla street. Block 10A - B10A - A1',	'Ahd_51'	);
insert into tmp_boundary (digitname,digitcode) values (	'Opposite Bajrang Akhara colony Area. Block 11A - B11A - A1',	'Ahd_52'	);
insert into tmp_boundary (digitname,digitcode) values (	'Both side Gala Mandi, Pansari Bazar, Sarfa Bazar, Sabji Mandi Block 12 - B12 - A1',	'Ahd_53'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sheller wali colony back side shajada Block 12 - B12 - A1',	'Ahd_54'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ashok Puri Mohalla, Bali Ram da hatta. Block 12 - B12 - A1',	'Ahd_55'	);
insert into tmp_boundary (digitname,digitcode) values (	'Janta College chowk upto chand cienma right side upto 20 foot deeply. Block 12 - B12 - A1',	'Ahd_56'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gandhi School Chowk upto right side mahesh sharam house. Block 13A - B13A - A1',	'Ahd_57'	);
insert into tmp_boundary (digitname,digitcode) values (	'Janta College chowk upto chand cienma right side upto 20 foot deeply Block 13A - B13A - A1',	'Ahd_58'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back side streets Janta college road, OPP. Gandhi School upto Ram Mandir Streets. Block 13A - B13A - A1',	'Ahd_59'	);
insert into tmp_boundary (digitname,digitcode) values (	'Baba Namdev walia streets, Saniara mohalla. Block 13A - B13A - A1',	'Ahd_60'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dahleez road Mahesh sharma house upto right side Octria. Block 13A - B13A - A1',	'Ahd_61'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sond cinema to channa road upto channa chowk. Block 14A - B14A - A1',	'Ahd_62'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gandhi school chowk to mahesh sharam house left side. Block 14A - B14A - A1',	'Ahd_63'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back side Area sood hospital Block 14A - B14A - A1',	'Ahd_64'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dahleez road to house of mahesh sharma upto left side octria. Block 14A - B14A - A1',	'Ahd_65'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jandali Crossing upto sond cinema about right side. Block 15 - B15 - A1',	'Ahd_66'	);
insert into tmp_boundary (digitname,digitcode) values (	'Lakhashmi ice factory. Block 15 - B15 - A1',	'Ahd_67'	);
insert into tmp_boundary (digitname,digitcode) values (	'All streets of krishna mandir Area, Near hind Hospital . Block 15 - B15 - A1',	'Ahd_68'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jandali Crossing upto sond cinema about left side. Block 16A - B16A - A1',	'Ahd_69'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sond Cinema to left side channa road about chhanna chowk. Block 16A - B16A - A1',	'Ahd_70'	);
insert into tmp_boundary (digitname,digitcode) values (	'Green Valley School Block 16A - B16A - A1',	'Ahd_71'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kaki Mata mandir Area. Block 16A - B16A - A1',	'Ahd_72'	);
insert into tmp_boundary (digitname,digitcode) values (	'Area Dr. B.R. Ambedakar Block 1B - B1B - A2',	'Ahd_73'	);
insert into tmp_boundary (digitname,digitcode) values (	'Swastik Colony back side Area. Block 1B - B1B - A2',	'Ahd_74'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back side bus stand and white house Area opposite Block 1B - B1B - A2',	'Ahd_75'	);
insert into tmp_boundary (digitname,digitcode) values (	'Link road Jandali Jandali Kurad Area (Malikpur) with for W.No 4 Block 2B - B2B - A2',	'Ahd_76'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagera crossing upto sheyans papers mill, from Jandali Canal to with is for Area W No 4 Area upto turn off Block 2B - B2B - A2',	'Ahd_77'	);
insert into tmp_boundary (digitname,digitcode) values (	'Area attached with railway boundry, from ludhiana octria limit upto jandali link road Away from 200 feet back side area upto limit (river) - B2B - A2',	'Ahd_78'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ludhiana malerkotla road comm and industry back side upto limit, Harjindra Marriage Palace bank side upto (limit) Block 2B - B2B - A2',	'Ahd_79'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagera road up to murdghat back side Area, Luvkus colony Area. Block 2B - B2B - A2',	'Ahd_80'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dhank basti Area. Block 9B - B9B - A2',	'Ahd_81'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bajrang Akhara road right side, chappar road , Som nath wal Area Block 10B - B10B - A2',	'Ahd_82'	);
insert into tmp_boundary (digitname,digitcode) values (	'All Area end of upto Tahsil road Block 10B - B10B - A2',	'Ahd_83'	);
insert into tmp_boundary (digitname,digitcode) values (	'Balmik basti som nath area. Block 11B - B11B - A2',	'Ahd_84'	);
insert into tmp_boundary (digitname,digitcode) values (	'Left side bajrang akhara road upto mukhtiar Singh poltary form Block Area 11B - B11B - A2',	'Ahd_85'	);
insert into tmp_boundary (digitname,digitcode) values (	'old Dahleez octrio area upto village chhanna. Block 11B - B11B - A2',	'Ahd_86'	);
insert into tmp_boundary (digitname,digitcode) values (	'Yakub streets, sodhi streets, Pandit khohi wali street, Dahleez octria murdghat wal Area. Block 13B - B13B - A2',	'Ahd_87'	);
insert into tmp_boundary (digitname,digitcode) values (	'Aala Masjid Area , streets of hari chand verma. Block 14B - B14B - A2',	'Ahd_88'	);
insert into tmp_boundary (digitname,digitcode) values (	'Guru Ravidass road both side, swalia transfer back side Area, Near kushi Diary Wala Area. Block 16B - B16B - A2',	'Ahd_89'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jandali Fatak upto going to village Chhanna right side Area and Jandali Octria wal Area Block 16B - B16B - A2',	'Ahd_90'	);

