insert into tmp_boundary (digitname,digitcode) values (	'ABADI SULTAAN PURA - B1 - A1',	'LC-1'	);
insert into tmp_boundary (digitname,digitcode) values (	'BADHA ROAD - B1 - A1',	'LC-15'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHAWLA COLONY - B1 - A1',	'LC-27'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHAWLA STREET - B1 - A1',	'LC-28'	);
insert into tmp_boundary (digitname,digitcode) values (	'DHINGRA COLONY - B1 - A2',	'LC-46'	);
insert into tmp_boundary (digitname,digitcode) values (	'DURGANA MANDIR - B1 - A1',	'LC-51'	);
insert into tmp_boundary (digitname,digitcode) values (	'FREEDOM FIGHTER ROAD - B1 - A1',	'LC-58'	);
insert into tmp_boundary (digitname,digitcode) values (	'JORA SINGH MANN NAGAR - B1 - A2',	'LC-80'	);
insert into tmp_boundary (digitname,digitcode) values (	'KUPPA STREET - B1 - A1',	'LC-95'	);
insert into tmp_boundary (digitname,digitcode) values (	'NEW ABADI ISLAMABAD - B1 - A2',	'LC-119'	);
insert into tmp_boundary (digitname,digitcode) values (	'NEW ABADI SULTANPURA - B1 - A2',	'LC-120'	);
insert into tmp_boundary (digitname,digitcode) values (	'PEER GURIA STREET - B1 - A2',	'LC-129'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAILWAY ROAD - B1 - A1',	'LC-138'	);
insert into tmp_boundary (digitname,digitcode) values (	'SADHU ASHARAM ROAD - B1 - A1',	'LC-152'	);
insert into tmp_boundary (digitname,digitcode) values (	'AMAR COLONY - B2 - A1',	'LC-7'	);
insert into tmp_boundary (digitname,digitcode) values (	'ARAYA NAGAR - B2 - A2',	'LC-9'	);
insert into tmp_boundary (digitname,digitcode) values (	'BHAGWATI PARSHAD STREET - B2 - A1',	'LC-20'	);
insert into tmp_boundary (digitname,digitcode) values (	'COURT ROAD - B2 - A1',	'LC-36'	);
insert into tmp_boundary (digitname,digitcode) values (	'DEAD ROAD - B2 - A1',	'LC-42'	);
insert into tmp_boundary (digitname,digitcode) values (	'DEENA NATH STREET - B2 - A1',	'LC-43'	);
insert into tmp_boundary (digitname,digitcode) values (	'DR. MOHAN SINGH STREET - B2 - A1',	'LC-50'	);
insert into tmp_boundary (digitname,digitcode) values (	'HAJUR SINGH BASTI - B2 - A1',	'LC-69'	);
insert into tmp_boundary (digitname,digitcode) values (	'HOTEL BAZAR - B2 - A1',	'LC-70'	);
insert into tmp_boundary (digitname,digitcode) values (	'KAILASH NAGAR - B2 - A1',	'LC-82'	);
insert into tmp_boundary (digitname,digitcode) values (	'KALKA MANDIR STREET - B2 - A1',	'LC-83'	);
insert into tmp_boundary (digitname,digitcode) values (	'KRISHNA STREET - B2 - A1',	'LC-92'	);
insert into tmp_boundary (digitname,digitcode) values (	'MEHAR CHAND STREET - B2 - A2',	'LC-111'	);
insert into tmp_boundary (digitname,digitcode) values (	'NAGPAL STREET - B2 - A1',	'LC-116'	);
insert into tmp_boundary (digitname,digitcode) values (	'NEHARU NAGAR - B2 - A2',	'LC-118'	);
insert into tmp_boundary (digitname,digitcode) values (	'PREM STREET - B2 - A1',	'LC-133'	);
insert into tmp_boundary (digitname,digitcode) values (	'SATSANG SCHOOL STREET - B2 - A1',	'LC-158'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHANDORA MOHALLA - B3 - A2',	'LC-25'	);
insert into tmp_boundary (digitname,digitcode) values (	'RADHA SWAMI COLONY - B3 - A2',	'LC-137'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAM SHARANAM COLONY - B3 - A1',	'LC-144'	);
insert into tmp_boundary (digitname,digitcode) values (	'SANJIV CINEMA ROAD - B3 - A1',	'LC-155'	);
insert into tmp_boundary (digitname,digitcode) values (	'BADAL COLONY - B4 - A2',	'LC-14'	);
insert into tmp_boundary (digitname,digitcode) values (	'BATHINDA ROAD - B4 - A1',	'LC-19'	);
insert into tmp_boundary (digitname,digitcode) values (	'BIKANERI ROAD - B4 - A1',	'LC-23'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHODRIAN STREET - B4 - A1',	'LC-30'	);
insert into tmp_boundary (digitname,digitcode) values (	'CO-OPERATIVE BANK STREET - B4 - A1',	'LC-35'	);
insert into tmp_boundary (digitname,digitcode) values (	'DABKARA STREET - B4 - A2',	'LC-38'	);
insert into tmp_boundary (digitname,digitcode) values (	'DASHMESH NAGAR - B4 - A2',	'LC-39'	);
insert into tmp_boundary (digitname,digitcode) values (	'DASONDI RAM STREET - B4 - A1',	'LC-40'	);
insert into tmp_boundary (digitname,digitcode) values (	'DAWRA STREET - B4 - A1',	'LC-41'	);
insert into tmp_boundary (digitname,digitcode) values (	'DHOBIYA STREET - B4 - A1',	'LC-48'	);
insert into tmp_boundary (digitname,digitcode) values (	'DHURIA STREET - B4 - A1',	'LC-49'	);
insert into tmp_boundary (digitname,digitcode) values (	'EK JOT COLONY - B4 - A1',	'LC-52'	);
insert into tmp_boundary (digitname,digitcode) values (	'GALI SODIYAN - B4 - A2',	'LC-59'	);
insert into tmp_boundary (digitname,digitcode) values (	'GANDHI NAGAR STREET - B4 - A1',	'LC-60'	);
insert into tmp_boundary (digitname,digitcode) values (	'GHUMAR STREET - B4 - A1',	'LC-66'	);
insert into tmp_boundary (digitname,digitcode) values (	'ISLAMIYAN SCHOOL - B4 - A2',	'LC-72'	);
insert into tmp_boundary (digitname,digitcode) values (	'JATTIEN MOHALLA - B4 - A2',	'LC-77'	);
insert into tmp_boundary (digitname,digitcode) values (	'KEWAL KAMRA STREET - B4 - A1',	'LC-87'	);
insert into tmp_boundary (digitname,digitcode) values (	'KUMHARA STREET - B4 - A1',	'LC-94'	);
insert into tmp_boundary (digitname,digitcode) values (	'M.C COLONY - B4 - A1',	'LC-97'	);
insert into tmp_boundary (digitname,digitcode) values (	'MADHAV NAGARI - B4 - A2',	'LC-99'	);
insert into tmp_boundary (digitname,digitcode) values (	'MAHRIA BAZAR - B4 - A1',	'LC-101'	);
insert into tmp_boundary (digitname,digitcode) values (	'MAHTAB GANJ ROAD - B4 - A1',	'LC-102'	);
insert into tmp_boundary (digitname,digitcode) values (	'MANI RAM STREET - B4 - A1',	'LC-107'	);
insert into tmp_boundary (digitname,digitcode) values (	'MASTER MASTAAN SINGH STREET - B4 - A1',	'LC-108'	);
insert into tmp_boundary (digitname,digitcode) values (	'MUNSHI RAM MEHRA STREET - B4 - A2',	'LC-114'	);
insert into tmp_boundary (digitname,digitcode) values (	'NAAMDEV NAGAR - B4 - A2',	'LC-115'	);
insert into tmp_boundary (digitname,digitcode) values (	'NIKKA RAM STREET - B4 - A2',	'LC-121'	);
insert into tmp_boundary (digitname,digitcode) values (	'PANSARIAN STREET - B4 - A1',	'LC-125'	);
insert into tmp_boundary (digitname,digitcode) values (	'PARAO ROAD - B4 - A1',	'LC-127'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAM JI LAL STREET - B4 - A2',	'LC-142'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAM PAL STREET - B4 - A2',	'LC-143'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAVI DASS NAGAR - B4 - A2',	'LC-148'	);
insert into tmp_boundary (digitname,digitcode) values (	'REGGAR CHOCK - B4 - A1',	'LC-149'	);
insert into tmp_boundary (digitname,digitcode) values (	'SACHDEVA STREET - B4 - A1',	'LC-150'	);
insert into tmp_boundary (digitname,digitcode) values (	'SAI DASS STREET - B4 - A1',	'LC-153'	);
insert into tmp_boundary (digitname,digitcode) values (	'SITA RAM MANDIR STREET - B4 - A2',	'LC-167'	);
insert into tmp_boundary (digitname,digitcode) values (	'SODHIA STREET - B4 - A2',	'LC-168'	);
insert into tmp_boundary (digitname,digitcode) values (	'STATE BANK STREET - B4 - A1',	'LC-170'	);
insert into tmp_boundary (digitname,digitcode) values (	'T.V TAWER COLONY - B4 - A2',	'LC-174'	);
insert into tmp_boundary (digitname,digitcode) values (	'VIJAY COLONY - B4 - A1',	'LC-177'	);
insert into tmp_boundary (digitname,digitcode) values (	'BHARO BASTI - B5 - A2',	'LC-21'	);
insert into tmp_boundary (digitname,digitcode) values (	'COLLEGE ROAD - B5 - A1',	'LC-33'	);
insert into tmp_boundary (digitname,digitcode) values (	'DHAKA BASTI - B5 - A2',	'LC-45'	);
insert into tmp_boundary (digitname,digitcode) values (	'KHATIKA MOHALA - B5 - A2',	'LC-89'	);
insert into tmp_boundary (digitname,digitcode) values (	'ODDAN BASTI - B5 - A2',	'LC-122'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAVADIA STREET - B5 - A1',	'LC-147'	);
insert into tmp_boundary (digitname,digitcode) values (	'SACHRAD HART SCHOOL - B5 - A1',	'LC-151'	);
insert into tmp_boundary (digitname,digitcode) values (	'SHAKTI NAGAR - B5 - A1',	'LC-163'	);
insert into tmp_boundary (digitname,digitcode) values (	'SULEMAAM KI ROAD STREET - B5 - A2',	'LC-171'	);
insert into tmp_boundary (digitname,digitcode) values (	'ABOHAR ROAD - B6 - A1',	'LC-2'	);
insert into tmp_boundary (digitname,digitcode) values (	'AGGERWAL STREET - B6 - A2',	'LC-4'	);
insert into tmp_boundary (digitname,digitcode) values (	'AHUJA STREET - B6 - A2',	'LC-5'	);
insert into tmp_boundary (digitname,digitcode) values (	'ARAYA SAMAJ ROAD - B6 - A1',	'LC-10'	);
insert into tmp_boundary (digitname,digitcode) values (	'BABU RAM STREET - B6 - A1',	'LC-13'	);
insert into tmp_boundary (digitname,digitcode) values (	'BAIJNATH STREET - B6 - A1',	'LC-16'	);
insert into tmp_boundary (digitname,digitcode) values (	'BAJAAJI BAZAR - B6 - A1',	'LC-17'	);
insert into tmp_boundary (digitname,digitcode) values (	'BHATHEJA STREET - B6 - A1',	'LC-22'	);
insert into tmp_boundary (digitname,digitcode) values (	'CANTT ROAD - B6 - A1',	'LC-24'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHUGH STREET - B6 - A1',	'LC-31'	);
insert into tmp_boundary (digitname,digitcode) values (	'CYCLE BAZAR - B6 - A1',	'LC-37'	);
insert into tmp_boundary (digitname,digitcode) values (	'FARSH NO:14 - B6 - A1',	'LC-54'	);
insert into tmp_boundary (digitname,digitcode) values (	'GARIB CHAND STREET - B6 - A1',	'LC-61'	);
insert into tmp_boundary (digitname,digitcode) values (	'GAU SHALA ROAD - B6 - A1',	'LC-62'	);
insert into tmp_boundary (digitname,digitcode) values (	'GEETA BHAVAN STREET - B6 - A1',	'LC-63'	);
insert into tmp_boundary (digitname,digitcode) values (	'GHAAS MANDI - B6 - A1',	'LC-64'	);
insert into tmp_boundary (digitname,digitcode) values (	'GHANTA GHAR CHOCK - B6 - A1',	'LC-65'	);
insert into tmp_boundary (digitname,digitcode) values (	'GYANI GURBAKASH SINGH STREET - B6 - A1',	'LC-68'	);
insert into tmp_boundary (digitname,digitcode) values (	'JANGALIAN STREET - B6 - A1',	'LC-75'	);
insert into tmp_boundary (digitname,digitcode) values (	'KAMRA STREET - B6 - A1',	'LC-84'	);
insert into tmp_boundary (digitname,digitcode) values (	'KHAJANCHIAN STREET - B6 - A1',	'LC-88'	);
insert into tmp_boundary (digitname,digitcode) values (	'KHATIYA STREET - B6 - A1',	'LC-90'	);
insert into tmp_boundary (digitname,digitcode) values (	'LAHORA MARKET - B6 - A1',	'LC-96'	);
insert into tmp_boundary (digitname,digitcode) values (	'MADAN GOPAL ROAD - B6 - A1',	'LC-98'	);
insert into tmp_boundary (digitname,digitcode) values (	'MAHESVARIA STREET - B6 - A1',	'LC-100'	);
insert into tmp_boundary (digitname,digitcode) values (	'MAHVEER FACTORY ROAD - B6 - A1',	'LC-103'	);
insert into tmp_boundary (digitname,digitcode) values (	'MEER SAHIB STREET - B6 - A1',	'LC-110'	);
insert into tmp_boundary (digitname,digitcode) values (	'NARANG STREET - B6 - A1',	'LC-117'	);
insert into tmp_boundary (digitname,digitcode) values (	'P.N.B BANK STREET - B6 - A1',	'LC-123'	);
insert into tmp_boundary (digitname,digitcode) values (	'PNB BANK STREET - B6 - A1',	'LC-132'	);
insert into tmp_boundary (digitname,digitcode) values (	'PUJARIAN STREET - B6 - A1',	'LC-134'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAJA CINEMA ROAD - B6 - A1',	'LC-140'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAMPAL STREET - B6 - A1',	'LC-146'	);
insert into tmp_boundary (digitname,digitcode) values (	'SARAAFA BAZAR - B6 - A1',	'LC-157'	);
insert into tmp_boundary (digitname,digitcode) values (	'SCHOOL NO:2 BACKSIDE - B6 - A1',	'LC-159'	);
insert into tmp_boundary (digitname,digitcode) values (	'SETH SHOPAT RAI STREET - B6 - A1',	'LC-161'	);
insert into tmp_boundary (digitname,digitcode) values (	'SHAM JI MAL STREET - B6 - A1',	'LC-164'	);
insert into tmp_boundary (digitname,digitcode) values (	'SHARAN DAS STREET - B6 - A1',	'LC-165'	);
insert into tmp_boundary (digitname,digitcode) values (	'ST.MAHINDER PARTAP DHINGRA. - B6 - A1',	'LC-169'	);
insert into tmp_boundary (digitname,digitcode) values (	'SUNDAR ASHRAM STREET - B6 - A1',	'LC-173'	);
insert into tmp_boundary (digitname,digitcode) values (	'TELIA STREET - B6 - A1',	'LC-176'	);
insert into tmp_boundary (digitname,digitcode) values (	'ADARSH NAGAR - B7 - A1',	'LC-3'	);
insert into tmp_boundary (digitname,digitcode) values (	'ALAM SHAH ROAD - B7 - A2',	'LC-6'	);
insert into tmp_boundary (digitname,digitcode) values (	'ANANDPUR MOHALLA - B7 - A2',	'LC-8'	);
insert into tmp_boundary (digitname,digitcode) values (	'ASHOKA COTTON FACTORY - B7 - A1',	'LC-11'	);
insert into tmp_boundary (digitname,digitcode) values (	'DHOBI GHAT - B7 - A2',	'LC-47'	);
insert into tmp_boundary (digitname,digitcode) values (	'FIRNI ROAD - B7 - A1',	'LC-56'	);
insert into tmp_boundary (digitname,digitcode) values (	'KANSHI RAM COLONY - B7 - A2',	'LC-85'	);
insert into tmp_boundary (digitname,digitcode) values (	'MALKANA MOHALLA - B7 - A1',	'LC-105'	);
insert into tmp_boundary (digitname,digitcode) values (	'PURANA HANUMAAN MANDIR - B7 - A1',	'LC-135'	);
insert into tmp_boundary (digitname,digitcode) values (	'RAMDEV NAGAR - B7 - A2',	'LC-145'	);
insert into tmp_boundary (digitname,digitcode) values (	'SEWAK SABHA - B7 - A2',	'LC-162'	);
insert into tmp_boundary (digitname,digitcode) values (	'AYIDAAN STREET - B8 - A1',	'LC-12'	);
insert into tmp_boundary (digitname,digitcode) values (	'CHITRU RAM STREET - B8 - A2',	'LC-29'	);
insert into tmp_boundary (digitname,digitcode) values (	'GILHOTRA STREET - B8 - A1',	'LC-67'	);
insert into tmp_boundary (digitname,digitcode) values (	'IDAAN STREET - B8 - A1',	'LC-71'	);
insert into tmp_boundary (digitname,digitcode) values (	'ISTRI BAWAN STREET - B8 - A1',	'LC-73'	);
insert into tmp_boundary (digitname,digitcode) values (	'JAIN MANDIR STREET - B8 - A1',	'LC-74'	);
insert into tmp_boundary (digitname,digitcode) values (	'JARGARAA STREET - B8 - A1',	'LC-76'	);
insert into tmp_boundary (digitname,digitcode) values (	'JHIVERA STREET - B8 - A2',	'LC-78'	);
insert into tmp_boundary (digitname,digitcode) values (	'JUNEJA STREET - B8 - A1',	'LC-81'	);
insert into tmp_boundary (digitname,digitcode) values (	'KASERIYA STREET - B8 - A1',	'LC-86'	);
insert into tmp_boundary (digitname,digitcode) values (	'KHUNGAR STREET - B8 - A1',	'LC-91'	);
insert into tmp_boundary (digitname,digitcode) values (	'KUKKARA STREET - B8 - A1',	'LC-93'	);
insert into tmp_boundary (digitname,digitcode) values (	'MAL SINGH STREET - B8 - A1',	'LC-104'	);
insert into tmp_boundary (digitname,digitcode) values (	'MASTER MULCHAND - B8 - A1',	'LC-109'	);
insert into tmp_boundary (digitname,digitcode) values (	'MOHAN LAL KUKKAR STREET - B8 - A1',	'LC-112'	);
insert into tmp_boundary (digitname,digitcode) values (	'MONGA STREET - B8 - A1',	'LC-113'	);
insert into tmp_boundary (digitname,digitcode) values (	'PANDIT RAM CHAND STREET - B8 - A1',	'LC-124'	);
insert into tmp_boundary (digitname,digitcode) values (	'PARAO ROAD - B8 - A1',	'LC-126'	);
insert into tmp_boundary (digitname,digitcode) values (	'PARNAMI MANDIR - B8 - A1',	'LC-128'	);
insert into tmp_boundary (digitname,digitcode) values (	'PHIRNI ROAD - B8 - A1',	'LC-130'	);
insert into tmp_boundary (digitname,digitcode) values (	'PURANI SABJI MANDI - B8 - A1',	'LC-136'	);
insert into tmp_boundary (digitname,digitcode) values (	'SALEM SHAH ROAD - B8 - A1',	'LC-154'	);
insert into tmp_boundary (digitname,digitcode) values (	'SCHOOL NO:3 - B8 - A1',	'LC-160'	);
insert into tmp_boundary (digitname,digitcode) values (	'SHIVPURI ROAD - B8 - A2',	'LC-166'	);
insert into tmp_boundary (digitname,digitcode) values (	'SUNARIA STREET - B8 - A1',	'LC-172'	);
insert into tmp_boundary (digitname,digitcode) values (	'BANK COLONY - B9 - A1',	'LC-18'	);
insert into tmp_boundary (digitname,digitcode) values (	'CIVIL LINE - B9 - A1',	'LC-32'	);
insert into tmp_boundary (digitname,digitcode) values (	'FEROZEPURI ROAD - B9 - A1',	'LC-55'	);
insert into tmp_boundary (digitname,digitcode) values (	'JHULE LAL COLONY - B9 - A1',	'LC-79'	);
insert into tmp_boundary (digitname,digitcode) values (	'CENTRAIL WARE HOUSE - B9 - A1',	'LC-156'	);
insert into tmp_boundary (digitname,digitcode) values (	'TEACHER COLONY - B9 - A2',	'LC-175'	);

