insert into  tmp_boundary (digitname,digitcode) values ( 	'Shanti Nagar - B1 - A1',	'NSR_1'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bhucharran Mohaala - B1 - A1',	'NSR_2'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Lalliyan Mohalla - B1 - A1',	'NSR_3'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Guru ki Beri - B1 - A1',	'NSR_4'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Chopra Gandhi Chowk - B1 - A1',	'NSR_5'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gali Rajpal - B1 - A1',	'NSR_6'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bodi bag - B1 - A1',	'NSR_7'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ghass mandi - B1 - A1',	'NSR_8'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bagicha - B1 - A1',	'NSR_9'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bibi verra - B1 - A1',	'NSR_10'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dadiyan Mohalla - B1 - A1',	'NSR_11'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shiv Colony Chowk - B1 - A1',	'NSR_12'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dadiyan Mohalla - B2 - A1',	'NSR_13'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dana Mandi - B2 - A1',	'NSR_14'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kirpa Gate - B2 - A1',	'NSR_15'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Indrapuri - B2 - A1',	'NSR_16'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ambedkar Nagar backside mandi - B2 - A1',	'NSR_17'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ravidass Nagar - B3 - A2',	'NSR_18'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Balmiki Mohalla - B3 - A2',	'NSR_19'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dalip Nagar - B3 - A1',	'NSR_20'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Khara Khu - B3 - A1',	'NSR_21'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ambedkar Nagar - B3 - A1',	'NSR_22'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Railway Road - B4 - A1',	'NSR_23'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Jain Street - B4 - A1',	'NSR_24'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dev Nagar - B4 - A1',	'NSR_25'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'New Adrash Nagar - B4 - A1',	'NSR_26'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Rishi Mohalla - B4 - A1',	'NSR_27'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kawar bazar - B4 - A1',	'NSR_28'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Nand lal street - B4 - A1',	'NSR_29'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shiv Nagar - B4 - A1',	'NSR_30'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Nehru Gate - B4 - A1',	'NSR_31'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Railway Station - B4 - A1',	'NSR_32'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Krishna Nagar - B4 - A1',	'NSR_33'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Geeta Bhawan Road - B5 - A1',	'NSR_34'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ganesh Nagar - B5 - A1',	'NSR_35'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Lal chowk - B5 - A1',	'NSR_36'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Laroyia Mohalla - B5 - A1',	'NSR_37'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ved Hem Raj Mohalla - B5 - A1',	'NSR_38'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shorian Mohalla - B5 - A1',	'NSR_39'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Committee bazar - B5 - A1',	'NSR_40'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Pathakan Mohalla - B5 - A1',	'NSR_41'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Vaida Gulshan bazar - B5 - A1',	'NSR_42'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Sharda Mohallla - B5 - A1',	'NSR_43'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Rerian bazar - B5 - A1',	'NSR_44'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gobindgarh Mohalla - B6 - A1',	'NSR_45'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Heera Jattan Mohalla - B6 - A1',	'NSR_46'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Mohan Nagar - B6 - A1',	'NSR_47'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Rajjan Mohalla - B6 - A1',	'NSR_48'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Arya Smaj Road - B6 - A1',	'NSR_49'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kulam Road - B7 - A1',	'NSR_50'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Chokkran Mohalla - B7 - A1',	'NSR_51'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Nayyar Mohalla - B7 - A1',	'NSR_52'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Lajpat Nagar - B7 - A1',	'NSR_53'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bagh Nijjran - B7 - A1',	'NSR_54'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Chandigarh Road - B7 - A1',	'NSR_55'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Barnala Road - B7 - A1',	'NSR_56'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Waheguru Nagar - B7 - A1',	'NSR_57'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Guru Angad Nagar - B7 - A1',	'NSR_58'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ranjeet Nagar - B7 - A1',	'NSR_59'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shivalik Enclave - B7 - A1',	'NSR_60'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Palika Bazar - B7 - A1',	'NSR_61'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shakti Nagar - B7 - A1',	'NSR_62'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Prince Enclave - B7 - A1',	'NSR_63'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kothi Road - B8 - A1',	'NSR_64'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kayian Mohalla - B8 - A1',	'NSR_65'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Umttan Mohalla - B8 - A1',	'NSR_66'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gali Talliyan - B8 - A1',	'NSR_67'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Awa Mohalla - B8 - A1',	'NSR_68'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Adarsh Nagar - B8 - A1',	'NSR_69'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Chetu bara Road - B8 - A1',	'NSR_70'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Mishra Mohalla - B8 - A1',	'NSR_71'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Pandora Mohalla - B9 - A1',	'NSR_72'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Prem Nagar - B9 - A1',	'NSR_73'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'New Prem Nagar - B9 - A1',	'NSR_74'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shiv Niketan - B9 - A1',	'NSR_75'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Court Road - B10 - A1',	'NSR_76'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Mota Singh Road - B10 - A1',	'NSR_77'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Guru Nanak Street - B10 - A1',	'NSR_78'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Saloh Road - B10 - A1',	'NSR_79'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Satguru Nagar - B10 - A1',	'NSR_80'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Friends Colony - B10 - A1',	'NSR_81'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Sirsa Colony - B10 - A1',	'NSR_82'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bhatti Colony - B10 - A1',	'NSR_83'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Nanak Nagar - B10 - A1',	'NSR_84'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Teacher Colony - B11 - A1',	'NSR_85'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'New Teacher Colony - B11 - A1',	'NSR_86'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Bakkarkhana Road - B11 - A1',	'NSR_87'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Mahallon Road - B11 - A2',	'NSR_88'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Shiv Colony - B11 - A1',	'NSR_89'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Sahid Udham Singh Nagar - B11 - A1',	'NSR_90'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Rahon Road - B12 - A1',	'NSR_91'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Baba Deep singh Nagar - B12 - A1',	'NSR_92'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Vikas Nagar - B12 - A1',	'NSR_93'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Navi Abadi - B13 - A2',	'NSR_94'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Karyam Road - B13 - A1',	'NSR_95'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Musapur Road - B13 - A2',	'NSR_96'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Ibrahim Basti - B13 - A2',	'NSR_97'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Aur Link Road - B13 - A1',	'NSR_98'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Killa Mohalla - B13 - A2',	'NSR_99'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Fateh Nagar - B14 - A1',	'NSR_100'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Dashmesh Nagar - B14 - A1',	'NSR_101'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Guru Teg Bhadur Nagar - B14 - A2',	'NSR_102'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gulzar Nagar - B14 - A1',	'NSR_103'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Saini Colony - B14 - A1',	'NSR_104'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Neelam Colony - B14 - A1',	'NSR_105'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Banga Road - B14 - A1',	'NSR_106'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Garhshankar Road - B15 - A1',	'NSR_107'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gali lakh data peer - B15 - A1',	'NSR_108'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Baba Shri Nand Nagar - B15 - A1',	'NSR_109'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Back side Tahli sahib G - B15 - A1',	'NSR_110'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Garhshankar Road & Banga Road By pass - B15 - A1',	'NSR_111'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kalra Mohalla - B15 - A2',	'NSR_112'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Gujjarpur Colony - B15 - A2',	'NSR_113'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Sant Nagar - B15 - A2',	'NSR_114'	);
insert into  tmp_boundary (digitname,digitcode) values ( 	'Kust Aarhram - B15 - A2',	'NSR_115'	);

