insert into tmp_boundary (digitname,digitcode) values (	'Sangrur Road - B1 - A1','SUN01'	);
insert into tmp_boundary (digitname,digitcode) values (	'Patiala Road - B1 - A1','SUN02'	);
insert into tmp_boundary (digitname,digitcode) values (	'Hanjra Road - B1 - A1','SUN03'	);
insert into tmp_boundary (digitname,digitcode) values (	'Indra Marg- North Side - B1 - A1','SUN04'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-1 - B1 - A1','SUN05'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-2 - B1 - A1','SUN06'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-3 - B1 - A1','SUN07'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-4 - B1 - A1','SUN08'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-5 - B1 - A1','SUN09'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-6 - B1 - A1','SUN10'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-7 - B1 - A1','SUN11'	);
insert into tmp_boundary (digitname,digitcode) values (	'Vishwakrma Raod, Sector-A, Street Number-8 - B1 - A1','SUN12'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-1 - B1 - A1','SUN13'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-2 - B1 - A1','SUN14'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-3 - B1 - A1','SUN15'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-4 - B1 - A1','SUN16'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-5 - B1 - A1','SUN17'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-6 - B1 - A1','SUN18'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-7 - B1 - A1','SUN19'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-B, Street Number-8 - B1 - A1','SUN20'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-1 - B1 - A1','SUN21'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-2 - B1 - A1','SUN22'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-3 - B1 - A1','SUN23'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-4 - B1 - A1','SUN24'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-5 - B1 - A1','SUN25'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-6 - B1 - A1','SUN26'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-7 - B1 - A1','SUN27'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-C, Street Number-8 - B1 - A1','SUN28'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-D, Street Number-1 - B1 - A1','SUN29'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-D, Street Number-2 - B1 - A1','SUN30'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-D, Street Number-3 - B1 - A1','SUN31'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-D, Street Number-4 - B1 - A1','SUN32'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ram Nagar, Indra Basti, Sector-D, Street Number-5 - B1 - A1','SUN33'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gurudwara Sachkhand-Patiala Road - B1 - A1','SUN34'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back Side 33 KVA Grid Patiala Road - B1 - A1','SUN35'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near BDPO Office - B1 - A1','SUN36'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near ITI, Court Complex-Patiala Road - B1 - A1','SUN37'	);
insert into tmp_boundary (digitname,digitcode) values (	'Taj City Colony - B1 - A1','SUN38'	);
insert into tmp_boundary (digitname,digitcode) values (	'Nambardar Colony - B1 - A1','SUN39'	);
insert into tmp_boundary (digitname,digitcode) values (	'Green City Colony - B1 - A1','SUN40'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jakhal Road-(Part-1) From ITI Chowk to Sheller Hari Kewal- Both Sides - B1 - A1','SUN41'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ajit Nagar - B1 - A1','SUN42'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gopal Nagar Near Imli Sahib Gurudwara - B1 - A1','SUN43'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Rishta Resort - B1 - A2','SUN44'	);
insert into tmp_boundary (digitname,digitcode) values (	'Scooter Market Near Rishta Resort - B1 - A2','SUN45'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back Side Civil Courts Colony - B1 - A2','SUN46'	);
insert into tmp_boundary (digitname,digitcode) values (	'Taraksheel Marg - B1 - A2','SUN47'	);
insert into tmp_boundary (digitname,digitcode) values (	'Parmanand Kutia - B1 - A2','SUN48'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back Side 66 KVA Grid Patiala Road - B1 - A2','SUN49'	);
insert into tmp_boundary (digitname,digitcode) values (	'Patiala Road Tata Kisaan Kendra to Rose Mary School - B1 - A2','SUN50'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back Side Maharaja Palace - B1 - A2','SUN51'	);
insert into tmp_boundary (digitname,digitcode) values (	'Back Side Gurudwara Moranwali - B1 - A2','SUN52'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dashmesh Nagar - B1 - A2','SUN53'	);
insert into tmp_boundary (digitname,digitcode) values (	'Balaji Colony to Bigharwal Road -Northern Side - B1 - A2','SUN54'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Sunam Gas Agency Godown- Biggharwal Road - B1 - A2','SUN55'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Sant Attar Singh School- Sheesha Singh De kothe - B1 - A2','SUN56'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jakhal Road ( Part-2) Bigharwal Chowk to Hariali -Nilowas NeharBoth Sides - B2 - A1','SUN57'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bigharwal Chowk to Railway Station indra Marg - B2 - A1','SUN58'	);
insert into tmp_boundary (digitname,digitcode) values (	'New Sabji Mandi - B2 - A1','SUN59'	);
insert into tmp_boundary (digitname,digitcode) values (	'New Grain Market - B2 - A1','SUN60'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sun City Colony - B2 - A1','SUN61'	);
insert into tmp_boundary (digitname,digitcode) values (	'VIP Enclave - B2 - A1','SUN62'	);
insert into tmp_boundary (digitname,digitcode) values (	'Maya Garden Colony - B2 - A1','SUN63'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road Noth Side - B2 - A1','SUN64'	);
insert into tmp_boundary (digitname,digitcode) values (	'Opposite NGM- Khadial Road Both Sides - B2 - A2','SUN65'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sadhan Wali Gali- Regar Basti - B2 - A2','SUN66'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dhanak Basti - B2 - A2','SUN67'	);
insert into tmp_boundary (digitname,digitcode) values (	'Hanumaan Mandir Wali Gali - B2 - A2','SUN68'	);
insert into tmp_boundary (digitname,digitcode) values (	'Munshi Wali Gali- Lal Chand Wali Gali - B2 - A2','SUN69'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road, Street Number-1 - B2 - A2','SUN70'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road, Street Number-2 - B2 - A2','SUN71'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road, Street Number-3 - B2 - A2','SUN72'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road, Street Number-4 - B2 - A2','SUN73'	);
insert into tmp_boundary (digitname,digitcode) values (	'Stadium Road, Street Number-5 - B2 - A2','SUN74'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gurdwara Hargobind Pura - B2 - A2','SUN75'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sandohe Wali Gali - B2 - A2','SUN76'	);
insert into tmp_boundary (digitname,digitcode) values (	'meenakshi Colonyy - B2 - A2','SUN77'	);
insert into tmp_boundary (digitname,digitcode) values (	'Backside Brijbala Hospital - B2 - A2','SUN78'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sensi Basti - B2 - A2','SUN79'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bigharwal Road West Side - B2 - A2','SUN80'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sant colony - B2 - A2','SUN81'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gurunanak Nagar - B2 - A2','SUN82'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Vishwas Hospital - B2 - A2','SUN83'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kutcha Paha - B2 - A2','SUN84'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gahir Colony - B2 - A2','SUN85'	);
insert into tmp_boundary (digitname,digitcode) values (	'Preet Nagar - B2 - A2','SUN86'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jagat pura near cotton Factory - B2 - A2','SUN87'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jawandha Road - B2 - A2','SUN88'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sant Kanda - B2 - A2','SUN89'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Cheema and Warehouse 2 Godown - B2 - A2','SUN90'	);
insert into tmp_boundary (digitname,digitcode) values (	'New Truck Union - B2 - A2','SUN91'	);
insert into tmp_boundary (digitname,digitcode) values (	'New Gaushala Road - B2 - A2','SUN92'	);
insert into tmp_boundary (digitname,digitcode) values (	'Deep Rice Mill Road - B2 - A2','SUN93'	);
insert into tmp_boundary (digitname,digitcode) values (	'New Tractor Trolly Union - B2 - A2','SUN94'	);
insert into tmp_boundary (digitname,digitcode) values (	'Hari Kewal Hospital - B2 - A2','SUN95'	);
insert into tmp_boundary (digitname,digitcode) values (	'Backside New Grain Market - B2 - A2','SUN96'	);
insert into tmp_boundary (digitname,digitcode) values (	'Aggarsain Cloth Market - B3 - A1','SUN97'	);
insert into tmp_boundary (digitname,digitcode) values (	'State Bank of Patiala- Street Number 1 - B3 - A1','SUN98'	);
insert into tmp_boundary (digitname,digitcode) values (	'State Bank of Patiala- Street Number 2 - B3 - A1','SUN99'	);
insert into tmp_boundary (digitname,digitcode) values (	'State Bank of Patiala- Street Number 3 - B3 - A1','SUN100'	);
insert into tmp_boundary (digitname,digitcode) values (	'Railway Crossing to Mata Modi Chowk - Both Sides - B3 - A1','SUN101'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gugga Maadi Road (West side) - B3 - A1','SUN102'	);
insert into tmp_boundary (digitname,digitcode) values (	'Aggarsain Chowk to Mal Godown - Both Sides - B3 - A1','SUN103'	);
insert into tmp_boundary (digitname,digitcode) values (	'SUS Cloth Markket - B3 - A1','SUN104'	);
insert into tmp_boundary (digitname,digitcode) values (	'Old Grain Market - B3 - A1','SUN105'	);
insert into tmp_boundary (digitname,digitcode) values (	'S.U.S. Cloth Market - B3 - A1','SUN106'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mata Modi Chowk to Cinema Chowk to Peeran wala Gate chowk - East Side - B3 - A1','SUN107'	);
insert into tmp_boundary (digitname,digitcode) values (	'Peeran Wala Gate to Nawa Bazaar to Mall Godown -North Side - B3 - A1','SUN108'	);
insert into tmp_boundary (digitname,digitcode) values (	'city road - B3 - A1','SUN109'	);
insert into tmp_boundary (digitname,digitcode) values (	'joshi market, geeta bhawan road - B3 - A1','SUN110'	);
insert into tmp_boundary (digitname,digitcode) values (	'dashmesh colony - B3 - A1','SUN111'	);
insert into tmp_boundary (digitname,digitcode) values (	'valmiki basti - B3 - A1','SUN112'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mata Modi Colony Back side Naina Devi Mandir - B3 - A1','SUN113'	);
insert into tmp_boundary (digitname,digitcode) values (	'krishna colony - B3 - A1','SUN114'	);
insert into tmp_boundary (digitname,digitcode) values (	'Shishu Bharti School Street - B3 - A1','SUN115'	);
insert into tmp_boundary (digitname,digitcode) values (	'From Extreme end of SBOP Street to Over Bridge - Street Number-1 - B3 - A2','SUN116'	);
insert into tmp_boundary (digitname,digitcode) values (	'From Extreme end of SBOP Street to Over Bridge - Street Number-2 - B3 - A2','SUN117'	);
insert into tmp_boundary (digitname,digitcode) values (	'From Extreme end of SBOP Street to Over Bridge - Street Number-3 - B3 - A2','SUN118'	);
insert into tmp_boundary (digitname,digitcode) values (	'sant attar singh nagar - B3 - A2','SUN119'	);
insert into tmp_boundary (digitname,digitcode) values (	'Modi Mill Chowk to under bridge to college - Both Sides - B4 - A1','SUN120'	);
insert into tmp_boundary (digitname,digitcode) values (	'Modi Mill Chowk to Nava Bazaar to Peeran wala Gate - West Side - B4 - A1','SUN121'	);
insert into tmp_boundary (digitname,digitcode) values (	'Rose Garden to Bhai Mool Chand Sahib College Road Railway Crossing- Northern Side - B4 - A1','SUN122'	);
insert into tmp_boundary (digitname,digitcode) values (	'Lajpat Rai Market - B4 - A1','SUN123'	);
insert into tmp_boundary (digitname,digitcode) values (	'Master colony - B4 - A1','SUN124'	);
insert into tmp_boundary (digitname,digitcode) values (	'Peer Banna Banoi Road - B4 - A1','SUN125'	);
insert into tmp_boundary (digitname,digitcode) values (	'kabir basti - B4 - A1','SUN126'	);
insert into tmp_boundary (digitname,digitcode) values (	'Peer banna banoi road (both sides) - B4 - A1','SUN127'	);
insert into tmp_boundary (digitname,digitcode) values (	'Rose Garden to Peeran Wala Gate Rotary School- Eastern Side - B4 - A1','SUN128'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bhai Mool Chand Sahib Colony - B4 - A2','SUN129'	);
insert into tmp_boundary (digitname,digitcode) values (	'College Road (Southern side) - B4 - A2','SUN130'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sarabha Nagar (Southern Side) - B4 - A2','SUN131'	);
insert into tmp_boundary (digitname,digitcode) values (	'Baba Ganga Ram Colony - B4 - A2','SUN132'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bakhtaur Nagar - B4 - A2','SUN133'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ekta Colony (Southern Side) - B4 - A2','SUN134'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near D.A.V. School (Southern Side) - B4 - A2','SUN135'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mata Modi Park to Dr. Purushotam Vashishath - B5 - A1','SUN136'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mata Modi Park to Moh. Tarkhana- Eastern Side - B5 - A2','SUN137'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohallan Raipurian - B5 - A2','SUN138'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dogran Wala Mohalla (Both Sides) - B5 - A2','SUN139'	);
insert into tmp_boundary (digitname,digitcode) values (	'Pathkan Wala Mohalla - B5 - A2','SUN140'	);
insert into tmp_boundary (digitname,digitcode) values (	'Charjan Wala Mohalla - B5 - A2','SUN141'	);
insert into tmp_boundary (digitname,digitcode) values (	'Deedar Tailor to Mata Modi Park- West Side - B5 - A2','SUN142'	);
insert into tmp_boundary (digitname,digitcode) values (	'Cinema Road to Ali Bazaar (Nothern Side) - B5 - A2','SUN143'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Baaran Hazaria -Jain Sathanak Road- Eastern Side - B5 - A2','SUN144'	);
insert into tmp_boundary (digitname,digitcode) values (	'Saraffa Bazaar (Northern Side) - B5 - A2','SUN145'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jaura Khoo to Cinema Road- West Side - B5 - A2','SUN146'	);
insert into tmp_boundary (digitname,digitcode) values (	'Rachbandeyan da mohalla - B5 - A2','SUN147'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Malkan - B5 - A2','SUN148'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Kaanjhliyan Wala - B5 - A2','SUN149'	);
insert into tmp_boundary (digitname,digitcode) values (	'Happy Home Colony - B6 - A1','SUN150'	);
insert into tmp_boundary (digitname,digitcode) values (	'Satya Enclave - B6 - A1','SUN151'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gaushala, Arora Colony - B6 - A1','SUN152'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gugga Maadi Road (Wast side) - B6 - A1','SUN153'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bhatinda Road Back Side Tralla Union - B6 - A2','SUN154'	);
insert into tmp_boundary (digitname,digitcode) values (	'PWD Resthouse- Backside Colony - B6 - A2','SUN155'	);
insert into tmp_boundary (digitname,digitcode) values (	'Lakhmir Wala Road - B6 - A2','SUN156'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dental College - B6 - A2','SUN157'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bagh Wali Colony - B6 - A2','SUN158'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gujjha Peer - B6 - A2','SUN159'	);
insert into tmp_boundary (digitname,digitcode) values (	'Namol Road - B6 - A2','SUN160'	);
insert into tmp_boundary (digitname,digitcode) values (	'220 KV Grid Namol Road - B6 - A2','SUN161'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Paradise School, Namol Road - B6 - A2','SUN162'	);
insert into tmp_boundary (digitname,digitcode) values (	'Atam Vallabh Jain ScHool - B6 - A2','SUN163'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Dhanwanti Filling Station - B6 - A2','SUN164'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sunder City Colony - B6 - A2','SUN165'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mehar Colony - B6 - A2','SUN166'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sitasar Mandir to Bhatinda Road - B6 - A2','SUN167'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ilaahi Chowk - B6 - A2','SUN168'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chohatta Bazaar - B6 - A2','SUN169'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohne Pauriyan - B6 - A2','SUN170'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Subhash Nagar - B6 - A2','SUN171'	);
insert into tmp_boundary (digitname,digitcode) values (	'Niyayi Sahib Dharamshala - B6 - A2','SUN172'	);
insert into tmp_boundary (digitname,digitcode) values (	'Punjab Public School - B6 - A2','SUN173'	);
insert into tmp_boundary (digitname,digitcode) values (	'Tarkhana Wala Mohalla - B6 - A2','SUN174'	);
insert into tmp_boundary (digitname,digitcode) values (	'Parmanand Basti - B6 - A2','SUN175'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bhaage Colony - B6 - A2','SUN176'	);
insert into tmp_boundary (digitname,digitcode) values (	'Anand Vihar to MC Office - B6 - A2','SUN177'	);
insert into tmp_boundary (digitname,digitcode) values (	'Opposite Rotary Public School - B7 - A1','SUN178'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chaman Beauty Parlour to Ravidas Dharamshala (Southern Side) - B7 - A1','SUN179'	);
insert into tmp_boundary (digitname,digitcode) values (	'Peer Gate Mohalla Bajra - B7 - A2','SUN180'	);
insert into tmp_boundary (digitname,digitcode) values (	'Old Munucipal Council - B7 - A2','SUN181'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dhibiyan Wala Mohalla - B7 - A2','SUN182'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla manjoran Wala - B7 - A2','SUN183'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jaura Khoo to Saraffa Bazaar (Southern Side) - B7 - A2','SUN184'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chotta Bazaar Near Doctor Khem Clinic - B7 - A2','SUN185'	);
insert into tmp_boundary (digitname,digitcode) values (	'Udham Jyoti Public School Street Near Dr. Popat (Both sides) - B7 - A2','SUN186'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chotta Bazaar (Eastern Side) - B7 - A2','SUN187'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Akalgarh Gurudwara - B7 - A2','SUN188'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhojeka (both sides) - B7 - A2','SUN189'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Rajan Wala (both sides) - B7 - A2','SUN190'	);
insert into tmp_boundary (digitname,digitcode) values (	'Dr. Chamak Chowk (Nothern Side) - B7 - A2','SUN191'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chaman Beauty Parlour to Ravidas Dharamshala (Southern Side) - B7 - A2','SUN192'	);
insert into tmp_boundary (digitname,digitcode) values (	'Thaana Sadar Road (Nothern side) - B7 - A2','SUN193'	);
insert into tmp_boundary (digitname,digitcode) values (	'Punjabi Bagh Colony - B8 - A2','SUN194'	);
insert into tmp_boundary (digitname,digitcode) values (	'Rose Garden to Basante di Kothi Road - B8 - A2','SUN195'	);
insert into tmp_boundary (digitname,digitcode) values (	'Manjora Mohalla - B8 - A2','SUN196'	);
insert into tmp_boundary (digitname,digitcode) values (	'Svuhan da Morcha - B8 - A2','SUN197'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Chhahrian Wala - B8 - A2','SUN198'	);
insert into tmp_boundary (digitname,digitcode) values (	'Raja Ram Street - B8 - A2','SUN199'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bhaika Mohalla - B8 - A2','SUN200'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Koko Majri - B8 - A2','SUN201'	);
insert into tmp_boundary (digitname,digitcode) values (	'Banda Basti - B8 - A2','SUN202'	);
insert into tmp_boundary (digitname,digitcode) values (	'Street Avtar Numberdaar - B8 - A2','SUN203'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near City Thana - B8 - A2','SUN204'	);
insert into tmp_boundary (digitname,digitcode) values (	'KaliCharan Basti - B8 - A2','SUN205'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kalicharan Mohalla Vaddi tainki - B8 - A2','SUN206'	);
insert into tmp_boundary (digitname,digitcode) values (	'Old Civil Court - B8 - A2','SUN207'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jakhepal Road East Side - B8 - A2','SUN208'	);
insert into tmp_boundary (digitname,digitcode) values (	'Bakshiwala Road (both sides) - B8 - A2','SUN209'	);
insert into tmp_boundary (digitname,digitcode) values (	'Neelowal Road - B8 - A2','SUN210'	);
insert into tmp_boundary (digitname,digitcode) values (	'Slaughter Road - B8 - A2','SUN211'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Punjabi Bagh Colony - B8 - A2','SUN212'	);
insert into tmp_boundary (digitname,digitcode) values (	'Patwar Khana - B9 - A2','SUN213'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Tarkhana Wala - B9 - A2','SUN214'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Sekhan Wala - B9 - A2','SUN215'	);
insert into tmp_boundary (digitname,digitcode) values (	'Chohatta BAzaar - B9 - A2','SUN216'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kailash Parbat - B9 - A2','SUN217'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhatta Wala - B9 - A2','SUN218'	);
insert into tmp_boundary (digitname,digitcode) values (	'Saraffa Bazaar (Nothern Side) - B9 - A2','SUN219'	);
insert into tmp_boundary (digitname,digitcode) values (	'Ali Bazaar (Western Side) - B9 - A2','SUN220'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhawdeyan Wala - B9 - A2','SUN221'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Tiyan Wala - B9 - A2','SUN222'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhadra Kali Mandir - B9 - A2','SUN223'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla bhattan wala - B9 - A2','SUN224'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Raipuriyan (Western Side) - B9 - A2','SUN225'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Peelwaad - B9 - A2','SUN226'	);
insert into tmp_boundary (digitname,digitcode) values (	'Rakesh Bhushan Residence to Mohall Bhawrian Wala- Western Side - B10 - A2','SUN227'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhangriyan Wala - B10 - A2','SUN228'	);
insert into tmp_boundary (digitname,digitcode) values (	'Gurdwara Pehli Padshahi Udham Singh Road - B10 - A2','SUN229'	);
insert into tmp_boundary (digitname,digitcode) values (	'Tagore Basti, Bawa Chownk - B10 - A2','SUN230'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Singhkiyan (Nothern Side) - B10 - A2','SUN231'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Kohliyan - B10 - A2','SUN232'	);
insert into tmp_boundary (digitname,digitcode) values (	'Backside Gurudwara Paatshahi Pehli - B10 - A2','SUN233'	);
insert into tmp_boundary (digitname,digitcode) values (	'Jakhepal Road Sotian Wale Peer (Western Side) - B10 - A2','SUN234'	);
insert into tmp_boundary (digitname,digitcode) values (	'Shaheed Udham Singh Road Dharamshala Road to Sheron Kenchian Gill Dhaba Sheron kenchian - Southern Side - B10 - A2','SUN235'	);
insert into tmp_boundary (digitname,digitcode) values (	'Sai Colony - B10 - A2','SUN236'	);
insert into tmp_boundary (digitname,digitcode) values (	'Taj Marriage Palace - B10 - A2','SUN237'	);
insert into tmp_boundary (digitname,digitcode) values (	'Paras Colony - B10 - A2','SUN238'	);
insert into tmp_boundary (digitname,digitcode) values (	'Neki Saraaf de Ghar to Saraafa Bazaar- Southern Side - B11 - A2','SUN239'	);
insert into tmp_boundary (digitname,digitcode) values (	'Tagore Basti (eastern side) to Government School - B11 - A2','SUN240'	);
insert into tmp_boundary (digitname,digitcode) values (	'Old Civil Court Road (Nothern Side) - B11 - A2','SUN241'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Bhojeka (western side) - B11 - A2','SUN242'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Tagore Basti - B11 - A2','SUN243'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Kanugo - B11 - A2','SUN244'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Singhkian (Southern side) - B11 - A2','SUN245'	);
insert into tmp_boundary (digitname,digitcode) values (	'Baazigar Basti - B11 - A2','SUN246'	);
insert into tmp_boundary (digitname,digitcode) values (	'Near Sukha Singh Dharamshala - B11 - A2','SUN247'	);
insert into tmp_boundary (digitname,digitcode) values (	'Mohalla Kanugo (Western side) - B11 - A2','SUN248'	);
insert into tmp_boundary (digitname,digitcode) values (	'Kalidas BAsti - B11 - A2','SUN249'	);
insert into tmp_boundary (digitname,digitcode) values (	'Government High School Backside Colony - B11 - A2','SUN250'	);

