/*
 * eGov Property Registry System.
 * APIs for Property Registry module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

/**
 * Value denoting if the unit is rented or occupied by owner
 */
public enum OccupancyType2 {
  OWNER("OWNER"),
  SELFOCCUPIED("SELFOCCUPIED"),
  TENANT("TENANT"),
  UNOCCUPIED("UNOCCUPIED"),
  RENTED("RENTED");

  private String value;

  OccupancyType2(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OccupancyType2 fromValue(String text) {
    for (OccupancyType2 b : OccupancyType2.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  
}
