/*
 * eGov Property Registry System.
 * APIs for Property Registry module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * OwnerInfo
 */

public class OwnerInfo extends User{
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("mobileNumber")
  private String mobileNumber = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("fatherOrHusbandName")
  private String fatherOrHusbandName = null;

  @JsonProperty("correspondenceAddress")
  private String correspondenceAddress = null;

  @JsonProperty("isPrimaryOwner")
  private Boolean isPrimaryOwner = null;

  @JsonProperty("ownerShipPercentage")
  private BigDecimal ownerShipPercentage = null;

  @JsonProperty("ownerType")
  private String ownerType = null;

  @JsonProperty("institutionId")
  private String institutionId = null;

  @JsonProperty("documents")
  private List<Document> documents = null;

  @JsonProperty("relationship")
  private Relationship relationship = null;

  @JsonProperty("additionalDetails")
  private Object additionalDetails = null;

  public OwnerInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the owner.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OwnerInfo mobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * MobileNumber of the owner.
   * @return mobileNumber
  **/
  public String getMobileNumber() {
    return mobileNumber;
  }

  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }

  public OwnerInfo gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender of the owner.
   * @return gender
  **/
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public OwnerInfo fatherOrHusbandName(String fatherOrHusbandName) {
    this.fatherOrHusbandName = fatherOrHusbandName;
    return this;
  }

   /**
   * Father or Husband name of the owner.
   * @return fatherOrHusbandName
  **/
  public String getFatherOrHusbandName() {
    return fatherOrHusbandName;
  }

  public void setFatherOrHusbandName(String fatherOrHusbandName) {
    this.fatherOrHusbandName = fatherOrHusbandName;
  }

  public OwnerInfo correspondenceAddress(String correspondenceAddress) {
    this.correspondenceAddress = correspondenceAddress;
    return this;
  }

   /**
   * The current address of the owner for correspondence.
   * @return correspondenceAddress
  **/
  public String getCorrespondenceAddress() {
    return correspondenceAddress;
  }

  public void setCorrespondenceAddress(String correspondenceAddress) {
    this.correspondenceAddress = correspondenceAddress;
  }

  public OwnerInfo isPrimaryOwner(Boolean isPrimaryOwner) {
    this.isPrimaryOwner = isPrimaryOwner;
    return this;
  }

   /**
   * The owner is primary or not
   * @return isPrimaryOwner
  **/
  public Boolean isIsPrimaryOwner() {
    return isPrimaryOwner;
  }

  public void setIsPrimaryOwner(Boolean isPrimaryOwner) {
    this.isPrimaryOwner = isPrimaryOwner;
  }

  public OwnerInfo ownerShipPercentage(BigDecimal ownerShipPercentage) {
    this.ownerShipPercentage = ownerShipPercentage;
    return this;
  }

   /**
   * Ownership percentage.
   * @return ownerShipPercentage
  **/
  public BigDecimal getOwnerShipPercentage() {
    return ownerShipPercentage;
  }

  public void setOwnerShipPercentage(BigDecimal ownerShipPercentage) {
    this.ownerShipPercentage = ownerShipPercentage;
  }

  public OwnerInfo ownerType(String ownerType) {
    this.ownerType = ownerType;
    return this;
  }

   /**
   * Type of owner, based on this option Exemptions will be applied. This is master data defined in mdms.
   * @return ownerType
  **/
  public String getOwnerType() {
    return ownerType;
  }

  public void setOwnerType(String ownerType) {
    this.ownerType = ownerType;
  }

  public OwnerInfo institutionId(String institutionId) {
    this.institutionId = institutionId;
    return this;
  }

   /**
   * The id of the institution if the owner is the authorized person for one
   * @return institutionId
  **/
  public String getInstitutionId() {
    return institutionId;
  }

  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }

  public OwnerInfo documents(List<Document> documents) {
    this.documents = documents;
    return this;
  }

  public OwnerInfo addDocumentsItem(Document documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<Document>();
    }
    this.documents.add(documentsItem);
    return this;
  }

   /**
   * The documents attached by owner for exemption.
   * @return documents
  **/
  public List<Document> getDocuments() {
    return documents;
  }

  public void setDocuments(List<Document> documents) {
    this.documents = documents;
  }

  public OwnerInfo relationship(Relationship relationship) {
    this.relationship = relationship;
    return this;
  }

   /**
   * Get relationship
   * @return relationship
  **/
  public Relationship getRelationship() {
    return relationship;
  }

  public void setRelationship(Relationship relationship) {
    this.relationship = relationship;
  }

  public OwnerInfo additionalDetails(Object additionalDetails) {
    this.additionalDetails = additionalDetails;
    return this;
  }

   /**
   * Json object to capture any extra information which is not accommodated of model
   * @return additionalDetails
  **/
  public Object getAdditionalDetails() {
    return additionalDetails;
  }

  public void setAdditionalDetails(Object additionalDetails) {
    this.additionalDetails = additionalDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OwnerInfo ownerInfo = (OwnerInfo) o;
    return Objects.equals(this.name, ownerInfo.name) &&
        Objects.equals(this.mobileNumber, ownerInfo.mobileNumber) &&
        Objects.equals(this.gender, ownerInfo.gender) &&
        Objects.equals(this.fatherOrHusbandName, ownerInfo.fatherOrHusbandName) &&
        Objects.equals(this.correspondenceAddress, ownerInfo.correspondenceAddress) &&
        Objects.equals(this.isPrimaryOwner, ownerInfo.isPrimaryOwner) &&
        Objects.equals(this.ownerShipPercentage, ownerInfo.ownerShipPercentage) &&
        Objects.equals(this.ownerType, ownerInfo.ownerType) &&
        Objects.equals(this.institutionId, ownerInfo.institutionId) &&
        Objects.equals(this.documents, ownerInfo.documents) &&
        Objects.equals(this.relationship, ownerInfo.relationship) &&
        Objects.equals(this.additionalDetails, ownerInfo.additionalDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mobileNumber, gender, fatherOrHusbandName, correspondenceAddress, isPrimaryOwner, ownerShipPercentage, ownerType, institutionId, documents, relationship, additionalDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OwnerInfo {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    fatherOrHusbandName: ").append(toIndentedString(fatherOrHusbandName)).append("\n");
    sb.append("    correspondenceAddress: ").append(toIndentedString(correspondenceAddress)).append("\n");
    sb.append("    isPrimaryOwner: ").append(toIndentedString(isPrimaryOwner)).append("\n");
    sb.append("    ownerShipPercentage: ").append(toIndentedString(ownerShipPercentage)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("    additionalDetails: ").append(toIndentedString(additionalDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
