/*
 * eGov Property Registry System.
 * APIs for Property Registry module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Contract class to send response.  Property items  is used in case of search results or response for search.
 */
public class PropertySearchResponse {
	 @JsonProperty("ResponseInfo")
	  private ResponseInfo responseInfo = null;

  @JsonProperty("Properties")
  private List<Property> properties = null;

public ResponseInfo getResponseInfo() {
	return responseInfo;
}

public void setResponseInfo(ResponseInfo responseInfo) {
	this.responseInfo = responseInfo;
}

public List< Property> getProperties() {
	return properties;
}

public void setProperties(List<Property> properties) {
	this.properties = properties;
}

  

}
