/*
 * eGov Water and Sewerage(W&S)  System.
 * APIs for W&S module. This provide APIs for create new property, update existing property, search existing property. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Contract class to receive request. Array of Property items  are used in case of create . Where as single Property item is used for update
 */
public class WaterConnectionRequest {
  @JsonProperty("RequestInfo")
  private RequestInfo requestInfo = null;

  @JsonProperty("WaterConnection")
  private WaterConnection waterConnection = null;

  public WaterConnectionRequest requestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
    return this;
  }

   /**
   * Get requestInfo
   * @return requestInfo
  **/
  public RequestInfo getRequestInfo() {
    return requestInfo;
  }

  public void setRequestInfo(RequestInfo requestInfo) {
    this.requestInfo = requestInfo;
  }

  public WaterConnectionRequest waterConnection(WaterConnection waterConnection) {
    this.waterConnection = waterConnection;
    return this;
  }

   /**
   * Get waterConnection
   * @return waterConnection
  **/
  public WaterConnection getWaterConnection() {
    return waterConnection;
  }

  public void setWaterConnection(WaterConnection waterConnection) {
    this.waterConnection = waterConnection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WaterConnectionRequest waterConnectionRequest = (WaterConnectionRequest) o;
    return Objects.equals(this.requestInfo, waterConnectionRequest.requestInfo) &&
        Objects.equals(this.waterConnection, waterConnectionRequest.waterConnection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestInfo, waterConnection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WaterConnectionRequest {\n");
    
    sb.append("    requestInfo: ").append(toIndentedString(requestInfo)).append("\n");
    sb.append("    waterConnection: ").append(toIndentedString(waterConnection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
